### PR TITLE
Adding a picture link to our footer design

### PR DESCRIPTION
**Pull request by xzhuah**
The picture link shows the current users profile picture and will redirect him to his profile page

### CODE REVIEW

**Comment by xzhuah** [comment]
Does everyone think the current design is good? I actually have to layout version for the user picture, the other is put it on the left

**Comment by iamacewhite** [comment]
How beautiful are we talking about? No photo you say **.

**Comment by water-vapor** [comment]
Can you show a photo of your design?

**Comment by Fengyee** [comment]
Hey, no photo no talk la~ @xzhuah

**Comment by LucenZhao** [comment]
I think the current makes the whole page more balanced. This one is better than putting it on the left!
Btw why the add user link is deleted in search event?

**Comment by water-vapor** [comment]
The current design does not contain links at footage, unlike the one shown in materialize template. Where did you put that link to make it look natural?

**Comment by xzhuah** [comment]
Maybe you guys can view a preview here : http://10.89.148.58:8080/teamform-seed/app/#/search

**Comment by iamacewhite** [comment]
Ha, How dare you downvote the project owner's comment? Do you wanna get merged or not　(┛`д´)┛

**Comment by iamacewhite** [comment]
# Looks neat

**Comment by xzhuah** [comment]
OK , Now I add the link to the picture, you will be able to go to your profile by clicking on the picture.

**Comment by hjiaa** [comment]
I found that when I click the profile picture, I will go to the bottom of the profile page rather than the top.

**Comment by xzhuah** [comment]
@hjiaa Thanks for finding that bug

**Comment by LucenZhao** [comment]
Found the same problem with @hjiaa

**Comment by xzhuah** [comment]
Anyone has any ideal about how to fix it?

**Comment by iamacewhite** [comment]
https://docs.angularjs.org/api/ng/service/$anchorScroll

**Comment by water-vapor** [comment]
@hjiaa @xzhuah I don't think it is caused by ZHU's great code. It is a general behavior that when you jump to other tabs, the page will keep its position. Since the footer is at he bottom, the shown profile page will be at the bottom.

**Comment by LucenZhao** [comment]
I guess the bug occurs bc the button is at the bottom of that page.
Could we just force it to scroll to top of the page by adding a #top on profile page?

**Comment by iamacewhite** [comment]
Bind a function to the click event, you can manually set $location.hash() to an element on top, then call $anchorScroll();

**Comment by hjiaa** [comment]
Agree with @LucenZhao 
Try this first.

**Comment by LucenZhao** [comment]
@iamacewhite  膜！

**Comment by water-vapor** [comment]
Why not follow the link white god provided? It says "This can be disabled by calling $anchorScrollProvider.disableAutoScrolling()."

**Comment by xzhuah** [comment]
wait I find a smart way to deal with the bug

**Comment by xzhuah** [comment]
@iamacewhite  You are right

**Comment by iamacewhite** [comment]
@xzhuah just proved that he is smarter than all of us combined.

**Comment by xzhuah** [comment]
@iamacewhite  you method is much better than mine. I have to use yours

**Comment by water-vapor** [comment]
@LucenZhao I am afraid we need a more general solution. In mobile app, there are many cases that a jump is performed when the scroller is not in the default position.

**Comment by xzhuah** [comment]
I have fixed that bug using jquery

**Comment by xzhuah** [comment]
image

**Comment by xzhuah** [comment]
I also adjusted the size of the image so that it looks awesome

**Comment by iamacewhite** [comment]
@yuwanzeon You are right. http://stackoverflow.com/questions/22779753/how-to-reset-scroll-position-on-a-route-change Maybe this can help

**Comment by water-vapor** [comment]
@xzhuah a new bug appeared: after you entering the profile page, the back button in the browser does not work properly.

**Comment by iamacewhite** [comment]
@yuwanzeon @xzhuah http://stackoverflow.com/questions/16967331/angular-js-browser-back-button-dosnt-work-when-routing

**Comment by iamacewhite** [comment]
Use #/ on link. it seems bug on angular js.`<td><a href="#/bio/{{doc.provider.Id}}"> {{doc.provider.FirstName}} </a></td>`

**Comment by xzhuah** [comment]
@iamacewhite  Good teach, thank you very much!

**Comment by iamacewhite** [comment]
This is how you insert a photo

**Comment by hjiaa** [comment]
screen shot 2016-11-16 at 5 07 05 pm
(problem on home page) oh is the reason that the user has't login?

**Comment by xzhuah** [comment]
If you want to show a picture on my component, remember to add a attribute called currenpic indicating the src of the img @hjiaa

**Comment by water-vapor** [comment]
@hjiaa I noticed it too. But it only happens occasionally(not fully reproducible). Can anyone find the condition to reproduce it?

**Comment by iamacewhite** [comment]
@xzhuah has already explained this. I am merging this PR now. Thank you for your contribution!

**Comment by xzhuah** [comment]
Thanks Good

**Comment by samuelzhouhe** [comment]
Yes the design is really beautiful.

**Pull request merged**
